### ISSUE TITLE
Fail to install dependencies via poetry

### ISSUE THREAD

**Issue by WEIFZH** [microsoft/Project-BayesDAG#18]
Thanks for your code, I am new to poetry. When I run "poetry install", the terminal shows like this 

> Path /home/code/Project-BayesDAG/open_source for causica does not exist

I have no idea how to fix it. Could you help me? Thanks

**Comment by zpmh** [comment]
I am having the same problem. Do you know how I could fix it? Thank you!

**Comment by zpmh** [comment]
It seemed to work for me by re-naming the "src" folder into "open_source" and running poetry install from within that folder. The README.md file also had to be duplicated/copied into the "open_source" folder.

**Comment by WEIFZH** [comment]
> It seemed to work for me by re-naming the "src" folder into "open_source" and running poetry install from within that folder. The README.md file also had to be duplicated/copied into the "open_source" folder.

Thanks a lot! it works for me too

**Comment by muhammadbaqirjafari** [comment]
> It seemed to work for me by re-naming the "src" folder into "open_source" and running poetry install from within that folder. The README.md file also had to be duplicated/copied into the "open_source" folder.

Do not need to rename, just run poetry inside src.
